version: '3'

services:
    web:
        build: ./docker
        container_name: "web"
        volumes:
            - ./:/usr/src/app
        working_dir: "/usr/src/app"
        ports:
            - "3000:3000"
        tty: true
        
